
[[_modules]]
= Modules
:subproject-base: {rootdir}/subprojects/griffon-nuvolaicons-
:java-source: /src/main/java/
:groovy-source: /src/main/groovy/
:package-base: org/codehaus/griffon/runtime/
:numbered:

The following sections display all bindings per module. Use this information to
successfully override a binding on your own modules or to troubleshoot a module
binding if the wrong type has been applied by the Griffon runtime.

== JavaFX

Module name: +nuvolaicons-javafx-groovy+

Depends on: +javafx-groovy+

[source,java,options="nowrap"]
----
include::{subproject-base}javafx-groovy{groovy-source}{package-base}/javafx/nuvolaicons/NuvolaIconsJavaFXGroovyModule.java[tags=bindings,indent=0]
----

The following nodes will become available on a Groovy View

[options="2*,header"]
|===
| Node     | Type
| nuvolaIcon | +{api_link_nuvolaicon_javafx}+
|===

== Swing

Module name: +nuvolaicons-swing-groovy+

Depends on: +swing-groovy+

[source,java,options="nowrap"]
----
include::{subproject-base}swing-groovy{java-source}{package-base}/swing/nuvolaicons/NuvolaIconsSwingGroovyModule.java[tags=bindings,indent=0]
----

The following nodes will become available on a Groovy View

[options="2*,header"]
|===
| Node     | Type
| nuvolaIcon | +{api_link_nuvolaicon_swing}+
|===

Both `nuvolaIcon` Nodes support the following properties

icon:: The name of the icon, such as +actions:back+ or +actions:forward+.
size:: The size of the icon. One of +16+, +22+, +32+, +48+, +64+, +128+.

NOTE: the +actions+ category is not supported in sizes bigger than +48+.

